package com.ijioio.aes.core;

/** Operation to use for {@link SearchQuery}. */
public enum Operation {
	EQUALS,
	NOT_EQUALS,
	LOWER,
	LOWER_OR_EQUALS,
	GREATER,
	GREATER_OR_EQUALS,
	ANY_EQUALS,
	ANY_NOT_EQUALS,
	ANY_LOWER,
	ANY_LOWER_OR_EQUALS,
	ANY_GREATER,
	ANY_GREATER_OR_EQUALS,
	ALL_EQUALS,
	ALL_NOT_EQUALS,
	ALL_LOWER,
	ALL_LOWER_OR_EQUALS,
	ALL_GREATER,
	ALL_GREATER_OR_EQUALS;
}
